### ISSUE TITLE
Be able to add files to ```/home``` folder / Poder agregar archivos a la carpeta ```/home``` [FEATURE]

### ISSUE THREAD

**Issue by Kedap** [Kedap/apmpkg#10]
**Describe the solution you'd like / Describe tu solucion**
A clear and concise description of what you want to happen. / Una descripcion clara y concisa de lo que quiere que haga

**Describe alternatives you've considered / Escriba las alternativas que a considerado**
Puts an example app.adi/ Como el siguiente ejemplo app.adi:
```toml
files = ["binary", "configdefault.conf"]
ruta = ["/usr/bin/binary", "$HOME/.config/app/configdefault.conf"]
```

**Additional context / Conteto adicional**
One of the things it would be useful for is to install [vim-plug](https://github.com/junegunn/vim-plug) / De las cosas por las que seria util es para instalar [vim-plug](https://github.com/junegunn/vim-plug)
