### ISSUE TITLE
Dependencies with commands / Dependencias con comandos [BUG]

### ISSUE THREAD

**Issue by Kedap** [Kedap/apmpkg#36]
**Describe the bug / Describe el bug**
 / Una descripción clara y concisa de cuál es el error.

In the [apmpkg documentation](https://github.com/Kedap/apmpkg/blob/main/doc/creando_paquetes_en.md#package) it says to verify that dependencies are installed by running commands, such as `make`. It is said that if it does not return another code output that is not 127, the dependency is considered installed, the problem is when the commands do not return output, it is the case of `nvim` `vim` `ftp` etc... /
En la [documentación de apmpkg](https://github.com/Kedap/apmpkg/blob/main/doc/creando_paquetes.md#paquete) se dice que se verifica que las dependencias esten instaladas mediante la ejecucion de comandos, como por ejemplo `make`. Se dice que si no retorna otra salida de codigo que no sea 127 se a por instalada la dependencia, el problema esta cuando los comandos no retornan salida, es el caso de `openssl` `elinks` `python` etc...

**To Reproduce / Como aparece el bug** 
Steps to reproduce the behavior: / Pasos para reproducir el bug:
1. Run / Ejecuto: `apmpkg crear adi test1`
2. I edit the file `test1.adi` / Edito el archivo `test1.adi`
3. Placed in the 'dependencies' array one of the aforementioned dependencies / Coloco en el array de 'dependencias' una de las dependencias antes mencionadas
4. The error appears / Aparece el error

**Expected behavior / Comportamiento esperado**
A clear and concise description of what you expected to happen. / Una descripcion clara de lo que deberia de pasar en vez del bug

Use some way to check these dependencies correctly / Use some way to check these dependencies correctly

**Screenshots / Captura de pantalla**
If applicable, add screenshots to help explain your problem. / Si es que aplica por favor coloque una captura de pantalla

There's no need / No es necesario

**Host machine info / Informacion de la maquina en donde se ejecuta**
 - OS: ArchLinux
 - Native package manager: Pacman
 - Version of ApmPKG 1.5.1

**Additional context / Contexto opcinal**
Add any other context about the problem here. / Si existe mas informacion importante para solucionar el error escribalo aqui

There's no need / No es necesario

**Comment by Kedap** [comment]
Tried to replicate the above but this only exists in the `nvim` and `vim` package. As a solution to this you can use the `cmd_depend` [array](https://github.com/Kedap/apmpkg/blob/main/doc/creando_paquetes_en.md#package) / Se intento replicar lo anterior pero este problema solo aparece cuando se utiliza los paquetes `nvim` y `vim`. Como solucion a esto se puede utilizar el [array](https://github.com/Kedap/apmpkg/blob/main/doc/creando_paquetes.md#paquete) `cmd_depend`

Example / Ejemplo:

```toml
[paquete]

nombre = "foo"
version = "1.0.0"
rama = "estable"
descrip = "Descripcion"
pagina = "https://foo.com/bar/"
licensia = "LICENSE"
dependencias = ["neovim", "vim"]
cmd_depend = ["nvim -v", "vim -h"]
conflicto = "/opt/tool-ac/"

[descarga]

url = "https://foo.com/bar/foo-bar.tar.gz"
carpeta = "foo-bar"
sha256sum = "SALTAR"

[instalacion]

pre_install = "pre_apmpkg.sh"
files = ["path/del/binario"]
ruta = ["/usr/bin/foobar"]
post_install = "post_apmpkg.sh"
```
